database:
  host: db_address.com
  port: 6543
  user: postgres
  password: dbpassword
  dbname: postgres
  sslmode: disable

ipinfo:
  token: TOKEN

connectivity:
  resolver: 1.1.1.1
  domain: example.com
  allowed_ports: [443, 80, 53, 5222, 5223, 5228]

  soax:
  mobile_package_id: 123456
  mobile_package_key: MobileKey
  residential_package_id: 789123
  residential_package_key: ResidentialKey
  endpoint: proxy.soax.com:5000
